<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span><ul class="toc-item"><li><span><a href="#Create-Numpy-Array-from-Python-List" data-toc-modified-id="Create-Numpy-Array-from-Python-List-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Create Numpy Array from Python List</a></span></li><li><span><a href="#Create-Numpy-Array-from-Built-in-Functions" data-toc-modified-id="Create-Numpy-Array-from-Built-in-Functions-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Create Numpy Array from Built-in Functions</a></span></li><li><span><a href="#Accessing,-Deleting-and-Inserting-Elements-into-NDArrays" data-toc-modified-id="Accessing,-Deleting-and-Inserting-Elements-into-NDArrays-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Accessing, Deleting and Inserting Elements into NDArrays</a></span></li><li><span><a href="#Slicing-NDArrays" data-toc-modified-id="Slicing-NDArrays-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Slicing NDArrays</a></span></li><li><span><a href="#Boolean-Indexing" data-toc-modified-id="Boolean-Indexing-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Boolean Indexing</a></span></li><li><span><a href="#Set-Operations" data-toc-modified-id="Set-Operations-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Set Operations</a></span></li><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Sorting</a></span></li></ul></li><li><span><a href="#Pandas" data-toc-modified-id="Pandas-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Pandas</a></span><ul class="toc-item"><li><span><a href="#Pandas-Series" data-toc-modified-id="Pandas-Series-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Pandas Series</a></span><ul class="toc-item"><li><span><a href="#Create" data-toc-modified-id="Create-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Create</a></span></li><li><span><a href="#Attributes" data-toc-modified-id="Attributes-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Attributes</a></span></li><li><span><a href="#Accessing-Data" data-toc-modified-id="Accessing-Data-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>Accessing Data</a></span></li><li><span><a href="#Modify-Series" data-toc-modified-id="Modify-Series-2.1.4"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span>Modify Series</a></span></li><li><span><a href="#Arithmetic-Operations" data-toc-modified-id="Arithmetic-Operations-2.1.5"><span class="toc-item-num">2.1.5&nbsp;&nbsp;</span>Arithmetic Operations</a></span></li></ul></li><li><span><a href="#Pandas-DataFrames" data-toc-modified-id="Pandas-DataFrames-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Pandas DataFrames</a></span><ul class="toc-item"><li><span><a href="#Create" data-toc-modified-id="Create-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Create</a></span></li><li><span><a href="#Attributes" data-toc-modified-id="Attributes-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Attributes</a></span></li><li><span><a href="#Accessing-Data" data-toc-modified-id="Accessing-Data-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Accessing Data</a></span><ul class="toc-item"><li><span><a href="#Access-column(s)-by-label" data-toc-modified-id="Access-column(s)-by-label-2.2.3.1"><span class="toc-item-num">2.2.3.1&nbsp;&nbsp;</span>Access column(s) by label</a></span></li><li><span><a href="#Access-column(s)-by-index" data-toc-modified-id="Access-column(s)-by-index-2.2.3.2"><span class="toc-item-num">2.2.3.2&nbsp;&nbsp;</span>Access column(s) by index</a></span></li><li><span><a href="#Access-row(s)-by-label" data-toc-modified-id="Access-row(s)-by-label-2.2.3.3"><span class="toc-item-num">2.2.3.3&nbsp;&nbsp;</span>Access row(s) by label</a></span></li><li><span><a href="#Access-row(s)-by-index" data-toc-modified-id="Access-row(s)-by-index-2.2.3.4"><span class="toc-item-num">2.2.3.4&nbsp;&nbsp;</span>Access row(s) by index</a></span></li><li><span><a href="#Get-N-rows-from-a-DF" data-toc-modified-id="Get-N-rows-from-a-DF-2.2.3.5"><span class="toc-item-num">2.2.3.5&nbsp;&nbsp;</span>Get N rows from a DF</a></span></li><li><span><a href="#Get-N-random-rows-from-a-DF" data-toc-modified-id="Get-N-random-rows-from-a-DF-2.2.3.6"><span class="toc-item-num">2.2.3.6&nbsp;&nbsp;</span>Get N random rows from a DF</a></span></li><li><span><a href="#Access-element-by-row-and-column-label" data-toc-modified-id="Access-element-by-row-and-column-label-2.2.3.7"><span class="toc-item-num">2.2.3.7&nbsp;&nbsp;</span>Access element by row and column label</a></span></li><li><span><a href="#Get-all-rows-where-column-value-satisfies-condition" data-toc-modified-id="Get-all-rows-where-column-value-satisfies-condition-2.2.3.8"><span class="toc-item-num">2.2.3.8&nbsp;&nbsp;</span>Get all rows where column value satisfies condition</a></span></li></ul></li><li><span><a href="#Modify-DF" data-toc-modified-id="Modify-DF-2.2.4"><span class="toc-item-num">2.2.4&nbsp;&nbsp;</span>Modify DF</a></span><ul class="toc-item"><li><span><a href="#Add-column" data-toc-modified-id="Add-column-2.2.4.1"><span class="toc-item-num">2.2.4.1&nbsp;&nbsp;</span>Add column</a></span></li><li><span><a href="#Append-columns-from-a-DF-to-another-DF" data-toc-modified-id="Append-columns-from-a-DF-to-another-DF-2.2.4.2"><span class="toc-item-num">2.2.4.2&nbsp;&nbsp;</span>Append columns from a DF to another DF</a></span></li><li><span><a href="#Insert-column-at-index" data-toc-modified-id="Insert-column-at-index-2.2.4.3"><span class="toc-item-num">2.2.4.3&nbsp;&nbsp;</span>Insert column at index</a></span></li><li><span><a href="#Add-column-using-sum-of-previous-columns-values" data-toc-modified-id="Add-column-using-sum-of-previous-columns-values-2.2.4.4"><span class="toc-item-num">2.2.4.4&nbsp;&nbsp;</span>Add column using sum of previous columns values</a></span></li><li><span><a href="#Add-rows" data-toc-modified-id="Add-rows-2.2.4.5"><span class="toc-item-num">2.2.4.5&nbsp;&nbsp;</span>Add rows</a></span></li><li><span><a href="#Delete-column" data-toc-modified-id="Delete-column-2.2.4.6"><span class="toc-item-num">2.2.4.6&nbsp;&nbsp;</span>Delete column</a></span></li><li><span><a href="#Delete-multiple-columns" data-toc-modified-id="Delete-multiple-columns-2.2.4.7"><span class="toc-item-num">2.2.4.7&nbsp;&nbsp;</span>Delete multiple columns</a></span></li><li><span><a href="#Delete-multiple-rows" data-toc-modified-id="Delete-multiple-rows-2.2.4.8"><span class="toc-item-num">2.2.4.8&nbsp;&nbsp;</span>Delete multiple rows</a></span></li><li><span><a href="#Transform-values-of-selected-columns" data-toc-modified-id="Transform-values-of-selected-columns-2.2.4.9"><span class="toc-item-num">2.2.4.9&nbsp;&nbsp;</span>Transform values of selected columns</a></span></li></ul></li><li><span><a href="#Dealing-with-NaN" data-toc-modified-id="Dealing-with-NaN-2.2.5"><span class="toc-item-num">2.2.5&nbsp;&nbsp;</span>Dealing with NaN</a></span></li><li><span><a href="#Statistical-Analysis" data-toc-modified-id="Statistical-Analysis-2.2.6"><span class="toc-item-num">2.2.6&nbsp;&nbsp;</span>Statistical Analysis</a></span></li></ul></li></ul></li><li><span><a href="#Data-Visualisation" data-toc-modified-id="Data-Visualisation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Visualisation</a></span></li><li><span><a href="#Anaconda" data-toc-modified-id="Anaconda-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Anaconda</a></span><ul class="toc-item"><li><span><a href="#List-envs" data-toc-modified-id="List-envs-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>List envs</a></span></li><li><span><a href="#Activate-env" data-toc-modified-id="Activate-env-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Activate env</a></span></li><li><span><a href="#Update-all-packages" data-toc-modified-id="Update-all-packages-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Update all packages</a></span></li><li><span><a href="#Install-package" data-toc-modified-id="Install-package-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Install package</a></span></li><li><span><a href="#Remove-package" data-toc-modified-id="Remove-package-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Remove package</a></span></li><li><span><a href="#Search-package" data-toc-modified-id="Search-package-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Search package</a></span></li><li><span><a href="#List-packages" data-toc-modified-id="List-packages-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>List packages</a></span></li></ul></li><li><span><a href="#Jupyter" data-toc-modified-id="Jupyter-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Jupyter</a></span><ul class="toc-item"><li><span><a href="#Convert-notebook-to-html" data-toc-modified-id="Convert-notebook-to-html-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Convert notebook to html</a></span></li><li><span><a href="#Add-TOC" data-toc-modified-id="Add-TOC-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Add TOC</a></span></li></ul></li></ul></div>

# Numpy

In [2]:
import numpy as np

## Create Numpy Array from Python List

In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)
print(type(x))
print(x.dtype)
print(x.shape)
print(x.size)

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x)
print(type(x))
print(x.dtype)
print(x.shape)
print(x.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
5
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
int64
(4, 3)
12


## Create Numpy Array from Built-in Functions

In [32]:
x = np.zeros((3, 4))
print(x)
print(x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [33]:
x = np.ones((3, 4), dtype=int)
print(x)
print(x.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [34]:
x = np.full((3, 4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
x = np.eye(5, dtype=int)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [36]:
x = np.diag([10, 20, 30, 40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [37]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [41]:
x = np.arange(1, 20, 3)
print(x)

[ 1  4  7 10 13 16 19]


In [42]:
x = np.linspace(1, 20, 3)
print(x)

[ 1.  10.5 20. ]


In [44]:
x = np.arange(20)
print(x)

x = np.reshape(x, (4, 5))
print(x)

x = np.arange(20).reshape(4, 5)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [48]:
# Defaults to range [0, 1)
x = np.random.random((3, 3))
print(x)

x = np.random.randint(4, 10, (3, 3))
print(x)

[[0.22087021 0.53229498 0.58663932]
 [0.21300366 0.86993844 0.56059265]
 [0.86554777 0.38157681 0.78204005]]
[[7 5 9]
 [7 4 7]
 [9 9 7]]


In [56]:
# mean = 0, std = 0.1
x = np.random.normal(0, 0.1, (5, 5))
print(x)

print(x.mean())
print(x.std())

[[ 0.0122765  -0.12708003  0.11426993 -0.04997364 -0.02526457]
 [-0.04439879 -0.12928117 -0.07242298  0.060275    0.06836317]
 [-0.02163878  0.15118322 -0.09682757 -0.04438684  0.11186937]
 [ 0.03933767 -0.08154594  0.00507315 -0.05448884  0.06592437]
 [ 0.06140125 -0.0002377  -0.07852702 -0.02126833  0.17878217]]
0.0008565443649252224
0.08241037010812466


## Accessing, Deleting and Inserting Elements into NDArrays

In [59]:
x = np.array([1, 2, 3, 4, 5])

print(x[0])
print(x[2])
print(x[-1])
print(x[-3])

1
3
5
3


In [105]:
## Get  diagonal of a 2d array

x = np.arange(25).reshape(5, 5)
print(x)

print(np.diag(x))
print(np.diag(x, k=1))
print(np.diag(x, k=-2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]
[ 1  7 13 19]
[10 16 22]


In [106]:
## Get unique elements of an array

x = np.array([1, 2, 3, 4, 2, 1, 1, 2, 5])
print(np.unique(x))

[1 2 3 4 5]


In [62]:
x = np.arange(1, 10).reshape(3, 3)

print(x)
print(x[0, 0])
print(x[1, 0])
print(x[2, 1])

## Modify element
x[2, 2] = -9
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
4
8
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -9]]


In [67]:
## Delete Rows by Index

x = np.arange(9).reshape(3, 3)
print(x)
print(np.delete(x, [0, 2], axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]]


In [70]:
## Delete Columns by Index

x = np.arange(9).reshape(3, 3)
print(x)
print(np.delete(x, [0, 2], axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [4]
 [7]]


In [72]:
## Append Row

x = np.arange(9).reshape(3, 3)
print(x)
print(np.append(x, [[9, 10, 11]], axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [74]:
## Append Column

x = np.arange(9).reshape(3, 3)
print(x)
print(np.append(x, [[9], [10], [11]], axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]


In [77]:
## Insert Elements - 1D / Rank 1 Arrays

x = np.array([1, 2, 5, 6, 7, 8, 9, 10])
print(x)
print(np.insert(x, 2, [3, 4]))

[ 1  2  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [79]:
## Insert Row at Specified Index - 2D Array

x = np.array([[1, 2, 3], [7, 8, 9]])
print(x)
print(np.insert(x, 1, [4, 5, 6], axis=0))

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
x = np.array([[1, 2], [4, 5]])
print(x)
print(np.insert(x, 2, [3, 6], axis=1))
print(np.insert(x, 2, 9, axis=1))

[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
[[1 2 9]
 [4 5 9]]


In [90]:
## Stack 2 Arrays - Vertically

x = np.array([1, 2])
y = np.array([[3, 4], [5, 6]])
print(f"x=\n{x}")
print(f"y=\n{y}")
print(f"vstack=\n {np.vstack((x, y))}")

x=
[1 2]
y=
[[3 4]
 [5 6]]
vstack=
 [[1 2]
 [3 4]
 [5 6]]


In [93]:
## Stack 2 Arrays - Horizontally

x = np.array([[3], [6]])
y = np.array([[1, 2], [4, 5]])
print(f"x=\n{x}")
print(f"y=\n{y}")
print(f"hstack=\n {np.hstack((y, x))}")

x=
[[3]
 [6]]
y=
[[1 2]
 [4 5]]
hstack=
 [[1 2 3]
 [4 5 6]]


## Slicing NDArrays

Slicing only creates new "views" on the original array, not new copies of the sliced array. To create a copy, use the `copy()` method.

In [99]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

print(x[0:2, 0:2])

## Notice the subtle difference between the followig
print(x[:, 0:1])
print(x[:, 0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2]
 [6 7]]
[[ 1]
 [ 6]
 [11]
 [16]]
[ 1  6 11 16]


## Boolean Indexing

In [109]:
x = np.arange(25).reshape(5, 5)
print(x)

print(x[(x > 10) & (x < 17)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16]


## Set Operations

In [110]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 8, 3, 2, 9])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 3]
[1 4 5]
[1 2 3 4 5 6 8 9]


## Sorting

In [119]:
x = np.random.randint(1, 11, size=(10, ))
print(x)

## Out-of-place sorting
print(f"oop sorted= \n {np.sort(x)}")
print(f"original= \n {x}")

## In-place sorting
x.sort()
print(f"ip sorted= \n {x}")

[9 1 8 9 6 1 7 6 2 8]
oop sorted= 
 [1 1 2 6 6 7 8 8 9 9]
original= 
 [9 1 8 9 6 1 7 6 2 8]
ip sorted= 
 [1 1 2 6 6 7 8 8 9 9]


# Pandas

In [121]:
import pandas as pd

## Pandas Series

### Create

In [128]:
### With default integer indices
groceries = pd.Series(data=[30, 6, 'Foo', 'Bar'])
print(groceries)

### With custom indices
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['egg', 'apples', 'milk', 'bread'])
print(groceries)

0     30
1      6
2    Foo
3    Bar
dtype: object
egg        30
apples      6
milk      Yes
bread      No
dtype: object


### Attributes

In [130]:
print(groceries.shape)
print(groceries.ndim)
print(groceries.size)
print(groceries.index)
print(groceries.values)
print('bananas' in groceries)
print('apples' in groceries)

(4,)
1
4
Index(['egg', 'apples', 'milk', 'bread'], dtype='object')
[30 6 'Yes' 'No']
False
True


### Accessing Data

In [144]:
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['egg', 'apples', 'milk', 'bread'])
print(groceries['egg'])

print('====\n')

## By labels
print(groceries[['egg', 'apples']])
print(groceries.loc[['egg', 'apples']])
print('====\n')

## By index
print(groceries[[0, -1]])
print(groceries.iloc[[0, -1]])

30
====

egg       30
apples     6
dtype: object
egg       30
apples     6
dtype: object
====

egg      30
bread    No
dtype: object
egg      30
bread    No
dtype: object


### Modify Series

In [145]:
## Change Element Values
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['egg', 'apples', 'milk', 'bread'])
groceries[['egg']] = 31
print(groceries)

egg        31
apples      6
milk      Yes
bread      No
dtype: object


In [153]:
## Drop Elements - Out-of-Place
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['egg', 'apples', 'milk', 'bread'])
print(groceries.drop(['apples']))
print(groceries)

egg       30
milk     Yes
bread     No
dtype: object
egg        30
apples      6
milk      Yes
bread      No
dtype: object


In [155]:
## Drop Elements - In-Place
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['egg', 'apples', 'milk', 'bread'])
groceries.drop(['apples'], inplace=True)
print(groceries)

egg       30
milk     Yes
bread     No
dtype: object


### Arithmetic Operations

In [157]:
fruits= pd.Series(data = [10, 6, 3,], index = ['apples', 'oranges', 'bananas'])
fruits + 1

apples     11
oranges     7
bananas     4
dtype: int64

In [158]:
np.sqrt(fruits)

apples     3.162278
oranges    2.449490
bananas    1.732051
dtype: float64

In [166]:
fruits[['bananas', 'oranges']] * 10

bananas    30
oranges    60
dtype: int64

## Pandas DataFrames

### Create

In [171]:
# We create a dictionary of Pandas Series 
items = {'Bob' : pd.Series(data = [245, 25, 55]),
         'Alice' : pd.Series(data = [40, 110, 500, 45])}

# We print the type of items to see that it is a dictionary
print(type(items))
shopping_carts = pd.DataFrame(items)
shopping_carts

<class 'dict'>


Bob  Alice
0  245.0     40
1   25.0    110
2   55.0    500
3    NaN     45

In [246]:
## Create DF from csv
# df = pd.read_csv('myfile.csv')

In [172]:
# We create a dictionary of Pandas Series 
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants'])}

# We print the type of items to see that it is a dictionary
print(type(items))
shopping_carts = pd.DataFrame(items)
shopping_carts

<class 'dict'>


Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

In [178]:
## Creating DF Using Subset of Dict

# We Create a DataFrame that only has selected items for Alice
alice_sel_shopping_cart = pd.DataFrame(items, index = ['glasses', 'bike'], columns = ['Alice'])
alice_sel_shopping_cart

Alice
glasses    110
bike       500

### Attributes

In [174]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants'])}
shopping_carts = pd.DataFrame(items)

shopping_carts.shape

(5, 2)

In [175]:
shopping_carts.ndim

2

In [176]:
shopping_carts.columns

Index(['Bob', 'Alice'], dtype='object')

In [177]:
shopping_carts.values

array([[245., 500.],
       [ nan,  40.],
       [ nan, 110.],
       [ 25.,  45.],
       [ 55.,  nan]])

### Accessing Data

In [265]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)
df

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

#### Access column(s) by label

In [266]:
df[['Bob', 'Alice']]

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

In [256]:
df.loc[:, ['Bob', 'Alice']]

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

#### Access column(s) by index

In [262]:
display(df)
df.iloc[:, [0, 2]]

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

Bob  Charlie
bike     245.0     70.0
book       NaN     45.0
glasses    NaN     90.0
pants     25.0    450.0
watch     55.0      NaN

#### Access row(s) by label

In [285]:
df.loc[['bike', 'pants']]

Bob  Alice  Charlie
bike   24500     40     4500
pants   2500    110     9000

#### Access row(s) by index

In [270]:
display(df)
df.iloc[[0, 2]]

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

Bob  Alice  Charlie
bike     245.0  500.0     70.0
glasses    NaN  110.0     90.0

#### Get N rows from a DF

In [287]:
df[:3]

Bob  Alice  Charlie
bike   24500     40     4500
pants   2500    110     9000
watch   5500    500     7000

#### Get N random rows from a DF

In [295]:
df.sample(n=2)

Bob  Alice  Charlie
watch  5500    500     7000
pants  2500    110     9000

#### Access element by row and column label

In [188]:
df['Alice']['bike']  # Column label always comes first

500.0

#### Get all rows where column value satisfies condition

In [259]:
display(df)
df.loc[df['Bob'] > 40]

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

Bob  Alice  Charlie
bike   245.0  500.0     70.0
watch   55.0    NaN      NaN

### Modify DF

In [212]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)
df

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

#### Add column

In [201]:
df['Dan'] = [1, 2, 3, 4, 5]
df

Bob  Alice  Charlie  Dan
bike     245.0  500.0     70.0    1
book       NaN   40.0     45.0    2
glasses    NaN  110.0     90.0    3
pants     25.0   45.0    450.0    4
watch     55.0    NaN      NaN    5

#### Append columns from a DF to another DF

In [272]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)
df

items_new = {'Dan' : pd.Series(data = [1, 2, 3], index = ['bike', 'pants', 'watch']),}
df_new = pd.DataFrame(items_new)
df.join(df_new)

Bob  Alice  Charlie  Dan
bike     245.0  500.0     70.0  1.0
book       NaN   40.0     45.0  NaN
glasses    NaN  110.0     90.0  NaN
pants     25.0   45.0    450.0  2.0
watch     55.0    NaN      NaN  3.0

#### Insert column at index

In [216]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)

df.insert(1, 'Dan', [1, 2, 3, 4, 5])
df

Bob  Dan  Alice  Charlie
bike     245.0    1  500.0     70.0
book       NaN    2   40.0     45.0
glasses    NaN    3  110.0     90.0
pants     25.0    4   45.0    450.0
watch     55.0    5    NaN      NaN

#### Add column using sum of previous columns values

In [217]:
df['Total'] = df['Bob'] + df['Alice'] + df['Charlie'] + df['Dan']
df

Bob  Dan  Alice  Charlie  Total
bike     245.0    1  500.0     70.0  816.0
book       NaN    2   40.0     45.0    NaN
glasses    NaN    3  110.0     90.0    NaN
pants     25.0    4   45.0    450.0  524.0
watch     55.0    5    NaN      NaN    NaN

#### Add rows

In [218]:
new_item = {'Bob': 1, 'Alice': 2, 'Charlie': 2}
new_df = pd.DataFrame(new_item, index = ['phones'])
display(new_df)

display(df.append(new_df))

Bob  Alice  Charlie
phones    1      2        2

Bob  Dan  Alice  Charlie  Total
bike     245.0  1.0  500.0     70.0  816.0
book       NaN  2.0   40.0     45.0    NaN
glasses    NaN  3.0  110.0     90.0    NaN
pants     25.0  4.0   45.0    450.0  524.0
watch     55.0  5.0    NaN      NaN    NaN
phones     1.0  NaN    2.0      2.0    NaN

#### Delete column

In [226]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)
display(df)
df.pop('Bob')
display(df)

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

Alice  Charlie
bike     500.0     70.0
book      40.0     45.0
glasses  110.0     90.0
pants     45.0    450.0
watch      NaN      NaN

#### Delete multiple columns

In [231]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450], index = ['book', 'glasses', 'bike', 'pants'])}

df = pd.DataFrame(items)
display(df)

display(df.drop(['Bob', 'Alice'], axis=1)) # 1 = columns

Bob  Alice  Charlie
bike     245.0  500.0     70.0
book       NaN   40.0     45.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0
watch     55.0    NaN      NaN

Charlie
bike        70.0
book        45.0
glasses     90.0
pants      450.0
watch        NaN

#### Delete multiple rows

In [232]:
display(df.drop(['watch', 'book'], axis=0)) # axis=0 => row / index

Bob  Alice  Charlie
bike     245.0  500.0     70.0
glasses    NaN  110.0     90.0
pants     25.0   45.0    450.0

#### Transform values of selected columns

In [281]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500], index = ['bike', 'pants', 'watch']),
         'Charlie': pd.Series(data = [45, 90, 70], index = ['bike', 'pants', 'watch'])}

df = pd.DataFrame(items)
display(df)

columns_to_tranform = ['Bob', 'Charlie']
df[columns_to_tranform] = df[columns_to_tranform].apply(lambda x: x * 100)
display(df)

Bob  Alice  Charlie
bike   245     40       45
pants   25    110       90
watch   55    500       70

Bob  Alice  Charlie
bike   24500     40     4500
pants   2500    110     9000
watch   5500    500     7000

In [284]:
#### Substitute values in columns of a DF
df.replace([40, 7000], ['Foo', 'Bar'])

Bob Alice Charlie
bike   24500   Foo    4500
pants   2500   110    9000
watch   5500   500     Bar

### Dealing with NaN

In [240]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Charlie': pd.Series(data = [45, 90, 70, 450, 1], index = ['book', 'glasses', 'bike', 'pants', 'watch'])}

df = pd.DataFrame(items)
display(df)

Bob  Alice  Charlie
bike     245.0  500.0       70
book       NaN   40.0       45
glasses    NaN  110.0       90
pants     25.0   45.0      450
watch     55.0    NaN        1

In [235]:
## Counting NaNs
df.isnull().sum().sum()

4

In [237]:
## Counting non-NaNs
df.count().sum()

11

In [238]:
## Drop rows with NaNs
display(df.dropna(axis=0))

Bob  Alice  Charlie
bike   245.0  500.0     70.0
pants   25.0   45.0    450.0

In [241]:
## Drop columns with NaNs
display(df.dropna(axis=1))

Charlie
bike          70
book          45
glasses       90
pants        450
watch          1

In [242]:
## Replace all NaNs with 0
display(df.fillna(0))

Bob  Alice  Charlie
bike     245.0  500.0       70
book       0.0   40.0       45
glasses    0.0  110.0       90
pants     25.0   45.0      450
watch     55.0    0.0        1

In [244]:
## Forward fill NaNs (value of previous row)
display(df)
display(df.fillna(method='ffill', axis=0)) # Other methods = 'backfill', 'linear'. Axis can be 1

Bob  Alice  Charlie
bike     245.0  500.0       70
book       NaN   40.0       45
glasses    NaN  110.0       90
pants     25.0   45.0      450
watch     55.0    NaN        1

Bob  Alice  Charlie
bike     245.0  500.0       70
book     245.0   40.0       45
glasses  245.0  110.0       90
pants     25.0   45.0      450
watch     55.0   45.0        1

### Statistical Analysis

In [247]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500], index = ['bike', 'pants', 'watch']),
         'Charlie': pd.Series(data = [45, 90, 70], index = ['bike', 'pants', 'watch'])}

df = pd.DataFrame(items)
display(df)

Bob  Alice  Charlie
bike   245     40       45
pants   25    110       90
watch   55    500       70

In [248]:
## Describe statistical information of DF
df.describe()

Bob       Alice    Charlie
count    3.000000    3.000000   3.000000
mean   108.333333  216.666667  68.333333
std    119.303534  247.857486  22.546249
min     25.000000   40.000000  45.000000
25%     40.000000   75.000000  57.500000
50%     55.000000  110.000000  70.000000
75%    150.000000  305.000000  80.000000
max    245.000000  500.000000  90.000000

In [249]:
df['Bob'].describeribe()

count      3.000000
mean     108.333333
std      119.303534
min       25.000000
25%       40.000000
50%       55.000000
75%      150.000000
max      245.000000
Name: Bob, dtype: float64

In [250]:
df.mean()

Bob        108.333333
Alice      216.666667
Charlie     68.333333
dtype: float64

In [251]:
df.max()

Bob        245
Alice      500
Charlie     90
dtype: int64

# Data Visualisation

TODO

# Anaconda

## List envs
```
conda info --envs
```

## Activate env
```
conda activate <env_name>
```

## Update all packages
```
conda upgrade -all
```

## Install package
```
conda install package_name

## specifying package version
conda install numpy=1.10
```

## Remove package
```
conda remove package_name
```

## Search package
```
conda search *search_term*
```

## List packages
```
conda list
```

# Jupyter

## Convert notebook to html
```
jupyter nbconvert --to html notebook.ipynb

# Other formats
# https://nbconvert.readthedocs.io/en/latest/usage.html
```

## Add TOC
Ref: https://towardsdatascience.com/jupyter-tools-to-increase-productivity-7b3c6b90be09